language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: KWJ6XXZ+xk6p+CPDwuPkal47p0RLPijbXPJWlhxJjjN9Xz2NHn7F5O8kp9m7BtPb+Pfb14mscPGKn39z7IqJSFNkXpW3/SKB4ogGr+VlP7chzNVuN7jqZmKF1nTxfrWuSunO2P984MFCVpSix3uul3ZHUrcTPBole/Ohbwb1y52objMhR+BExvixcoT6yEkEtHhhMXUXK7fRtSmVvZQlT2bXg2d9NXgfXE+0isiUK4bHtoW8JkAs6zNdKY1B94ZOV5y/x6yOaVZWVJXV6M3YPqrnG21HfU3EMNt5IsV/Ze5C4QtCBESw/7gFL+YpXMpeeFW9CmkdDqbxaya/VvFuiyHfOqWq+KtcbIOI6g6A+jDJeW3tSJH9JCOzr+CDFkWvDq/0pgGQokWpGRMnugvFOI5DpwU7mn0gxFc/3P27LWmeOwqYCkCMPGuX8pyihjPNMjFp2lsk2v3RgTkXdZEYnMaxZa+RkI6rmIBZlWkp5bBkIFJTH5CpNPbQwEDQHLJua9boeMTjWhX+NawCFrFdo7g3AJHDW+r7LYhtig7QRnwqXGacOzIbXZ+nmhGP5ryqLw1MMb9w0BqZP8qtmW2LcCRngWL/rc1N+Vi6RPAEEpuJ0U5okETztfnDtS96gHW4MaooLRq1M10VGJl+Vyp5ztgLM5zuLNrLida1dRceqrQ=
