name: ZeroSuit
main: com.doctorwood73.zerosuit.main.ZeroSuit
version: 0.1
authors: [Jwood9198, Jacc734]
commands:
   zerog:
      description:
         This 0 argument command will list all areas that are zero-gravity regions
      usage:
         /<command>
      permission:
         ZeroSuit.areaset
   zerog:
      description:
         This 2 argument command will remove a specified zero-gravity region
      usage:
         /<command><remove><nameID>
      permission:
         ZeroSuit.areaset
   zerog:
      description:
         This 8 argument command will create a zero-gravity region in the world you're in (overworld | nether | end) at the given coordinates
      usage:
         /<command><add><x1><y1><z1><x2><y2><z2><nameID>
      permission:
         ZeroSuit.areaset
   zerogfast:
      description:
         Changes your flying speed to 2
      usage:
         /<command>
      permission:
         ZeroSuit.speed
   zerogslow:
      description:
         Changes your flying speed to 1
      usage:
         /command>
      permission:
         ZeroSuit.speed
   zeroghelp:
      description:
         Lists All ZeroSuit Commands
      usage:
         /<command>
      permission:
         ZeroSuit.help
Permissions:
   ZeroSuit.zerog: 
      description:  Gives permission to create and remove 0 gravity areas
      default: op
   ZeroSuit.zerogfast:
      description:  Allows use of /zerogfast command (keep same default as zerogslow)
      default: true
   ZeroSuit.zerogslow:
      description:  Allows use of /zerogslow command (keep same default as zerogfast)
      default: true
   ZeroSuit.zeroghelp:
      description:  Allows use of /zeroghelp command
      default: true
